"""
prepare_pointai_training.py — converts D:/PointAIData/dataset into
CubiCasa-compatible LMDB layout ready for finetune.py.

Each folder in the dataset must contain:
  - original.jpg (or original.png)
  - label.npy    (generated by label_converter.py)
  - heatmaps.json (generated by label_converter.py)

Usage:
    python -m training.prepare_pointai_training --dataset D:/PointAIData/dataset --output D:/PointAIData/training
    python -m training.prepare_pointai_training --dataset D:/PointAIData/dataset --output D:/PointAIData/training --start 12 --end 221
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any

import cv2
import numpy as np

from training.common import (
    ConvertedSample,
    empty_heatmaps,
    load_jsonl,
    save_converted_sample,
    write_jsonl,
)
from training.create_unified_index import create_unified_index
from training.export_lmdb import export_splits_to_cubi_layout

DATASET_NAME = "pointai"


def load_sample(folder: Path) -> ConvertedSample | None:
    # Find image
    image_path = folder / "original.jpg"
    if not image_path.exists():
        image_path = next(folder.glob("original.*"), None)
    if image_path is None:
        return None

    label_path = folder / "label.npy"
    heatmaps_path = folder / "heatmaps.json"
    if not label_path.exists():
        return None

    # Load image as CHW float32 in [0,1]
    img_bgr = cv2.imread(str(image_path))
    if img_bgr is None:
        return None
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
    image_chw = np.moveaxis(img_rgb, -1, 0)  # HWC -> CHW

    # Load label
    label = np.load(str(label_path))

    # Load heatmaps
    heatmaps = empty_heatmaps()
    if heatmaps_path.exists():
        raw = json.loads(heatmaps_path.read_text(encoding="utf-8"))
        for k, v in raw.items():
            heatmaps[int(k)] = [tuple(pt) for pt in v]

    h, w = label.shape[-2], label.shape[-1]

    return ConvertedSample(
        dataset=DATASET_NAME,
        sample_id=folder.name,
        source_id=folder.name,
        image=image_chw,
        label=label,
        heatmaps=heatmaps,
        scale=1.0,
        meta={"source": "pointai", "folder": folder.name, "image_w": w, "image_h": h},
    )


def prepare_pointai_training(
    *,
    dataset_path: Path,
    output_root: Path,
    start: int = 1,
    end: int = 9999,
    seed: int = 13,
) -> dict[str, Any]:
    converted_dir = output_root / "converted"
    index_dir = output_root / "index"
    cubi_dir = output_root / "cubi_layout"

    converted_dir.mkdir(parents=True, exist_ok=True)

    folders = sorted(
        f for f in dataset_path.iterdir()
        if f.is_dir() and f.name.isdigit() and start <= int(f.name) <= end
    )

    manifest: list[dict[str, Any]] = []
    done = skipped = errors = 0

    for folder in folders:
        sample = load_sample(folder)
        if sample is None:
            skipped += 1
            continue

        try:
            record = save_converted_sample(sample, converted_dir, write_preview=False)
            manifest.append(record)
            done += 1
            print(f"  {folder.name} OK  ({sample.image.shape[1]}x{sample.image.shape[2]})")
        except Exception as e:
            print(f"  {folder.name} ERROR: {e}")
            errors += 1

    manifest_path = converted_dir / "pointai_manifest.jsonl"
    write_jsonl(manifest_path, manifest)
    print(f"\nManifest: {len(manifest)} samples -> {manifest_path}")

    # Train/val/test split (80/10/10)
    splits = create_unified_index([manifest_path], index_dir, seed=seed)
    print(f"Splits: train={len(splits['train'])}  val={len(splits['val'])}  test={len(splits['test'])}")

    # Export to LMDB
    layout = export_splits_to_cubi_layout(
        manifest_path=manifest_path,
        split_dir=index_dir,
        output_dir=cubi_dir,
        overwrite=True,
    )

    summary = {
        "dataset_path": str(dataset_path),
        "output_root": str(output_root),
        "done": done,
        "skipped": skipped,
        "errors": errors,
        "split_counts": {k: len(v) for k, v in splits.items()},
        "cubi_layout": layout,
    }
    (output_root / "prepare_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"\nLMDB listo en: {cubi_dir}")
    print(f"Para entrenar:\n  python -m training.finetune --data-path {cubi_dir} --run-dir {output_root}/runs")
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare PointAI dataset for CubiCasa fine-tuning.")
    parser.add_argument("--dataset", type=Path, default=Path("D:/PointAIData/dataset"))
    parser.add_argument("--output",  type=Path, default=Path("D:/PointAIData/training"))
    parser.add_argument("--start",   type=int,  default=1)
    parser.add_argument("--end",     type=int,  default=9999)
    parser.add_argument("--seed",    type=int,  default=13)
    args = parser.parse_args()

    prepare_pointai_training(
        dataset_path=args.dataset,
        output_root=args.output,
        start=args.start,
        end=args.end,
        seed=args.seed,
    )


if __name__ == "__main__":
    main()
