"""
lisp_writer.py — JSON floor plan → AutoLISP string
Uses the same room-based schema as generator.py but outputs LISP
instead of DXF, so it can be loaded directly in AutoCAD via MCP.

Usage:
    from scripts.lisp_writer import plan_to_lisp
    lisp = plan_to_lisp(plan_dict)
    with open("C:/temp/plan.lsp", "w") as f:
        f.write(lisp)
"""
from __future__ import annotations
import sys
from pathlib import Path

# Allow running as script from project root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.components.walls import (
    collect_walls, dedup_walls, merge_spans, split_segments, THICKNESS
)

# ── AutoCAD layer colors (index colors) ────────────────────────────────────
LAYER_DEFS = {
    "WALLS": 7,
    "DOORS": 157,
    "WINS":  121,
}

SLAB_THICKNESS = 1.5  # door slab thickness, inches


# ── Public API ──────────────────────────────────────────────────────────────

def plan_to_lisp(plan: dict) -> str:
    """Convert a floor plan JSON dict to a complete AutoLISP script string."""
    lines: list[str] = []
    lines.append("; Generated by Point.ai - png_to_autocad pipeline")
    lines.append('(command "UNDO" "BEGIN")')
    lines.append("")

    # Setup layers
    lines += _setup_layers()
    lines.append("")

    # Collect wall geometry (reuses existing logic)
    rooms = plan.get("rooms", [])
    h_walls, v_walls = collect_walls(rooms)
    v_walls = dedup_walls(v_walls)

    # Draw walls
    lines.append('; ── WALLS ─────────────────────────────────────')
    lines += _set_layer("WALLS")
    for y, spans in h_walls.items():
        for x1, x2, merged_gaps in merge_spans(spans):
            lines += _wall_h(x1, x2, y, merged_gaps)

    for x, spans in v_walls.items():
        for y1, y2, merged_gaps in merge_spans(spans):
            lines += _wall_v(x, y1, y2, merged_gaps)
    lines.append("")

    # Draw doors and windows per room
    lines.append('; ── DOORS ─────────────────────────────────────')
    lines += _set_layer("DOORS")
    for room in rooms:
        lines += _doors_for_room(room)
    lines.append("")

    lines.append('; ── WINDOWS ───────────────────────────────────')
    lines += _set_layer("WINS")
    for room in rooms:
        lines += _windows_for_room(room)
    lines.append("")

    lines.append('(command "UNDO" "END")')
    lines.append('(command "ZOOM" "E")')
    lines.append('(princ "\\nPoint.ai: floor plan loaded.")')
    lines.append("(princ)")
    return "\n".join(lines)


# ── Layer setup ─────────────────────────────────────────────────────────────

def _setup_layers() -> list[str]:
    cmds = ["; Setup Pointe Homes layers"]
    for name, color in LAYER_DEFS.items():
        cmds.append(f'(command "-LAYER" "MAKE" "{name}" "COLOR" "{color}" "{name}" "")')
    return cmds


def _set_layer(name: str) -> list[str]:
    return [f'(command "-LAYER" "SET" "{name}" "")']


# ── Wall drawing ─────────────────────────────────────────────────────────────

def _pt(x: float, y: float) -> str:
    return f'"{x:.4f},{y:.4f}"'


def _line(x1: float, y1: float, x2: float, y2: float) -> str:
    return f'(command "LINE" {_pt(x1, y1)} {_pt(x2, y2)} "")'


def _arc_center(cx: float, cy: float, radius: float, start_deg: float, sweep_deg: float) -> str:
    """ARC via center, start point, included angle."""
    import math
    rad = math.radians(start_deg)
    sx = cx + radius * math.cos(rad)
    sy = cy + radius * math.sin(rad)
    return (
        f'(command "ARC" "C" {_pt(cx, cy)} {_pt(sx, sy)} "A" "{sweep_deg:.1f}")'
    )


def _wall_h(x1: float, x2: float, y: float, gaps: list) -> list[str]:
    T = THICKNESS
    cmds = []
    for sx1, sx2 in split_segments(x1, x2, gaps):
        cmds.append(_line(sx1, y, sx2, y))
        cmds.append(_line(sx1, y + T, sx2, y + T))
    for gx1, gx2 in gaps:
        cmds.append(_line(gx1, y, gx1, y + T))
        cmds.append(_line(gx2, y, gx2, y + T))
    return cmds


def _wall_v(x: float, y1: float, y2: float, gaps: list) -> list[str]:
    T = THICKNESS
    cmds = []
    for sy1, sy2 in split_segments(y1, y2, gaps):
        cmds.append(_line(x, sy1, x, sy2))
        cmds.append(_line(x + T, sy1, x + T, sy2))
    for gy1, gy2 in gaps:
        cmds.append(_line(x, gy1, x + T, gy1))
        cmds.append(_line(x, gy2, x + T, gy2))
    return cmds


# ── Door drawing ─────────────────────────────────────────────────────────────

def _door(hx: float, hy: float, width: float, direction: str) -> list[str]:
    DS = SLAB_THICKNESS
    cmds = []
    if direction == "up":
        cmds.append(_line(hx, hy, hx, hy + width))
        cmds.append(_line(hx + DS, hy, hx + DS, hy + width))
        cmds.append(_arc_center(hx, hy, width, 0, 90))
    elif direction == "down":
        cmds.append(_line(hx, hy, hx, hy - width))
        cmds.append(_line(hx + DS, hy, hx + DS, hy - width))
        cmds.append(_arc_center(hx, hy, width, 270, 90))
    elif direction == "right":
        cmds.append(_line(hx, hy, hx + width, hy))
        cmds.append(_line(hx, hy + DS, hx + width, hy + DS))
        cmds.append(_arc_center(hx, hy, width, 0, 90))
    elif direction == "left":
        cmds.append(_line(hx, hy, hx - width, hy))
        cmds.append(_line(hx, hy + DS, hx - width, hy + DS))
        cmds.append(_arc_center(hx, hy, width, 90, 90))
    return cmds


def _doors_for_room(room: dict) -> list[str]:
    T = THICKNESS
    rx, ry, rw, rh = room["x"], room["y"], room["w"], room["h"]
    cmds = []
    for d in room.get("doors", []):
        if d.get("type") == "garage":
            continue
        off, w, wall = d["offset"], d["width"], d["wall"]
        if wall == "bottom":
            cmds += _door(rx + off, ry + T, w, "up")
        elif wall == "top":
            cmds += _door(rx + off, ry + rh - T, w, "down")
        elif wall == "left":
            cmds += _door(rx + T, ry + off, w, "right")
        elif wall == "right":
            cmds += _door(rx + rw - T, ry + off, w, "left")
    return cmds


# ── Window drawing ────────────────────────────────────────────────────────────

def _window_h(x: float, y: float, width: float, side: str) -> list[str]:
    cmds = []
    if side == "bottom":
        cmds.append(_line(x, y - 5, x + width, y - 5))   # sill
        cmds.append(_line(x, y,     x + width, y))
        cmds.append(_line(x, y - 1, x + width, y - 1))
        cmds.append(_line(x, y - 2, x + width, y - 2))
        cmds.append(_line(x,         y - 1, x,         y - 2))
        cmds.append(_line(x + width, y - 1, x + width, y - 2))
    else:  # top
        cmds.append(_line(x, y + 5, x + width, y + 5))
        cmds.append(_line(x, y,     x + width, y))
        cmds.append(_line(x, y + 1, x + width, y + 1))
        cmds.append(_line(x, y + 2, x + width, y + 2))
        cmds.append(_line(x,         y + 1, x,         y + 2))
        cmds.append(_line(x + width, y + 1, x + width, y + 2))
    return cmds


def _window_v(x: float, y: float, width: float, side: str) -> list[str]:
    T = THICKNESS
    cmds = []
    if side == "left":
        cmds.append(_line(x - 1, y, x - 1, y + width))
        cmds.append(_line(x,     y, x,     y + width))
        cmds.append(_line(x + 1, y, x + 1, y + width))
        cmds.append(_line(x + 6, y, x + 6, y + width))
        cmds.append(_line(x - 1, y,         x, y))
        cmds.append(_line(x - 1, y + width, x, y + width))
    else:  # right
        cmds.append(_line(x + T + 1, y, x + T + 1, y + width))
        cmds.append(_line(x + T,     y, x + T,     y + width))
        cmds.append(_line(x + T - 1, y, x + T - 1, y + width))
        cmds.append(_line(x - 2,     y, x - 2,     y + width))
        cmds.append(_line(x + T, y,         x + T + 1, y))
        cmds.append(_line(x + T, y + width, x + T + 1, y + width))
    return cmds


def _windows_for_room(room: dict) -> list[str]:
    T = THICKNESS
    rx, ry, rw, rh = room["x"], room["y"], room["w"], room["h"]
    cmds = []
    for wn in room.get("windows", []):
        off, w, wall = wn["offset"], wn["width"], wn["wall"]
        if wall == "bottom":
            cmds += _window_h(rx + off, ry, w, "bottom")
        elif wall == "top":
            cmds += _window_h(rx + off, ry + rh, w, "top")
        elif wall == "left":
            cmds += _window_v(rx, ry + off, w, "left")
        elif wall == "right":
            cmds += _window_v(rx + rw - T, ry + off, w, "right")
    return cmds


# ── CLI ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import json
    if len(sys.argv) < 2:
        print("Usage: python lisp_writer.py plan.json [output.lsp]")
        sys.exit(1)
    with open(sys.argv[1]) as f:
        plan = json.load(f)
    lisp = plan_to_lisp(plan)
    out = sys.argv[2] if len(sys.argv) > 2 else "C:/temp/plan.lsp"
    with open(out, "w", encoding="utf-8") as f:
        f.write(lisp)
    print(f"Written: {out}")
